baseURL = "https://heap.zip/"
title = "The Blog"
languageCode = "en-us"

pagination.pagerSize = 10

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"

[markup.goldmark.parser.attribute]
  block = true

[markup.highlight]
  noClasses = false

[params]
  description = "A minimal, themeless Hugo blog"
  author = "Content on this site is licensed CC BY-NC-SA 4.0"
